/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extended from "./extended";
export type { extended };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
import type * as mocks from "./mocks";
export type { mocks };
export type { BTCLFixedLottery } from "./BTCLFixedLottery";
export type { LotteryReceiver } from "./LotteryReceiver";
export type { LotterySender } from "./LotterySender";
