/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  LotteryManager,
  LotteryManagerInterface,
} from "../../../contracts/extended/LotteryManager";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "ADDRESS_ZERO",
    type: "error",
  },
  {
    inputs: [],
    name: "NOT_MANAGER",
    type: "error",
  },
  {
    inputs: [],
    name: "manager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newManager",
        type: "address",
      },
    ],
    name: "transferManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506000805460ff196101003302166001600160a81b03199091161790556103628061003c6000396000f3fe608060405234801561001057600080fd5b50600436106100675760003560e01c80635c975abb116100505780635c975abb146100c55780638456cb59146100e2578063ba0e930a146100ea57600080fd5b80633f4ba83a1461006c578063481c6a7514610076575b600080fd5b6100746100fd565b005b60005461009b90610100900473ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff90911681526020015b60405180910390f35b6000546100d29060ff1681565b60405190151581526020016100bc565b61007461017d565b6100746100f83660046102ef565b610200565b600054610100900473ffffffffffffffffffffffffffffffffffffffff163314610153576040517f9be16b5a00000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b600080547fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00169055565b600054610100900473ffffffffffffffffffffffffffffffffffffffff1633146101d3576040517f9be16b5a00000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b600080547fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00166001179055565b600054610100900473ffffffffffffffffffffffffffffffffffffffff163314610256576040517f9be16b5a00000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b73ffffffffffffffffffffffffffffffffffffffff81166102a3576040517f66e7950900000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b6000805473ffffffffffffffffffffffffffffffffffffffff909216610100027fffffffffffffffffffffff0000000000000000000000000000000000000000ff909216919091179055565b60006020828403121561030157600080fd5b813573ffffffffffffffffffffffffffffffffffffffff8116811461032557600080fd5b939250505056fea2646970667358221220bb8b61de89d17f52eed77490fcf253f152695fe85411f1ea9063d6882757f11064736f6c63430008110033";

type LotteryManagerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LotteryManagerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LotteryManager__factory extends ContractFactory {
  constructor(...args: LotteryManagerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LotteryManager> {
    return super.deploy(overrides || {}) as Promise<LotteryManager>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LotteryManager {
    return super.attach(address) as LotteryManager;
  }
  override connect(signer: Signer): LotteryManager__factory {
    return super.connect(signer) as LotteryManager__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LotteryManagerInterface {
    return new utils.Interface(_abi) as LotteryManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LotteryManager {
    return new Contract(address, _abi, signerOrProvider) as LotteryManager;
  }
}
